# Generated by Django 5.1.5 on 2025-01-31 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_curriculummapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurriculumMapping',
        ),
    ]
