# Generated by Django 5.1.5 on 2025-01-31 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_delete_curriculummapping'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_mappings', to='course.course')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_mappings', to='curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'Curriculum Mapping',
                'verbose_name_plural': 'Curriculum Mappings',
                'unique_together': {('curriculum', 'course')},
            },
        ),
    ]
